### ISSUE TITLE
Feature Request: Crowd Bypass Integration

### ISSUE THREAD

**Issue by DRSDavidSoft** [tacohitbox/bypass-it-for-me#2]
Hi there,

I just discovered your project and I'm impressed!

I was wondering if you could add a feature to send the bypassed URLs to crowd bypass databases, such as one provided by the [FastForward](https://github.com/FastForwardTeam/FastForward/) team (formerly maintained by [Universal-Bypass](https://github.com/Sainan/Universal-Bypass)), e.g.

```javascript
let xhr = new XMLHttpRequest()
xhr.open("POST","https://crowd.fastforward.team/crowd/contribute_v1",true)
xhr.setRequestHeader("Content-Type","application/x-www-form-urlencoded")
xhr.send(data) // {domain: "example.com", path: "<source_path>", target: "http://.../"}
```

This would be _very_ useful, as the instances of **BIFM** could share the cached bypassed links, which is most useful when say a user would like to bypass the same link using the browser extensions.

The format to contribute is as follows:
```
POST https://crowd.fastforward.team/crowd/contribute_v1 HTTP/1.1
Host: crowd.fastforward.team
Content-Type: application/x-www-form-urlencoded

domain=example.com&path=<source_path>&target=<url_encoded_path_to_target>
```

If you so choose, you can also fetch cached data from the crowd bypass database (if available), before actually bypassing it server side.

It would be awesome if BIFM could share cached data between instances, and browser extensions in this way! 😄 

Thank you

**Comment by DRSDavidSoft** [comment]
@tacohitbox thanks for adding this feature!

**Comment by tacohitbox** [comment]
forgot to close this after adding it. thanks :)
